### ISSUE TITLE
Any chance of wrapping Jinja?

### ISSUE THREAD

**Issue by kylemacfarlane** [orf/django-debug-toolbar-template-timings#20]
I was pretty surprised at how slow the Django templates could get. I popped in some Jinga templates using django-jinga and saw 2300ms drop to 290ms. However I couldn't see it yet in the panel.

It was pretty easy to wrap the basic Jinga rendering but I'm not sure about wrapping blocks.

The import:
```
try:
    from jinja2.environment import Environment
    jinja2 = True
except ImportError:
    jinja2 = False
```
The new name getter (pass in the `args` and `kwargs` from `timing_hook`).
```
    def name(self, args, kwargs):
        if hasattr(self, 'name'):
            name = self.name
        elif jinja2:
            if len(args) > 1:
                name = args[1]
            else:
                name = kwargs.get('name')
        return name or ''
```
The wrapper:
```
        if jinja2:
            Environment.compile = _template_render_wrapper(
                Environment.compile, "templates",
                lambda n: not any([re.match(pattern, n) for pattern in TEMPLATE_TIMINGS_SETTINGS["IGNORED_TEMPLATES"]])
            )
```

Also I was surprised at how plug and play django-jinga is and the immediate results. It uses a middleware to redirect all templates ending with e.g "j.html" to Jinga and so you don't have to redo all your templates at once.

**Comment by auvipy** [comment]
as django now officially supports jinja2 template backend

**Comment by dorianamouroux** [comment]
Still no support for jinja 2 ?

**Comment by orf** [comment]
Hi, this plugin was written by me a long time ago to fill a particular need. I open sourced it and it seems it became moderately popular, but I haven't used it in 3+ years.

If anyone wants to step in and add this feature, or work on it in any way, then I will always review and merge suitable PRs. Until them I'm afraid I don't have the time or the energy to add this.
